name: PR testen

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  test:
    name: Tests ausf√ºhren
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}

      - name: Abh√§ngigkeiten laden
        run: npm ci

      - name: Code formatieren
        run: npm run format-all

      - name: Add corresponding commit
        run: |
          git config --global user.name 'OpenFoxes Maintenance Bot'
          git config --global user.email 'openfoxes@bono-fox.de'
          git checkout ${{ github.event.pull_request.head.ref }}
          git add .
          git diff-index --quiet ${{ github.event.pull_request.head.ref }} || {
          git commit -m "üé® Code formatiert"
          git push origin ${{ github.event.pull_request.head.ref }}
          }

      - name: Alle Tests ausf√ºhren
        run: npm run test-cov-headless

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
